name: Kitchen Terraform Setup for Ops
on:
  repository_dispatch:
    types: [kitchen-terraform]
  workflow_dispatch:
    inputs:
      ref:
        description: 'github branch reference number'
        required: true
        default: 'Mona the Octocat'
      sha:
        description: 'github branch sha commit ID'
        required: true
        default: 'The Octoverse'
jobs:
  kitchenTest:
    runs-on: ubuntu-latest
    container: amitkuamrdube/kitchen-terraform:latest
    env : 
      GOOGLE_APPLICATION_CREDENTIALS: "my-first-project-298218-7e25767dcc93.json"
    steps:
      - name: Printing the inputs
        run: |
          echo "Ref - ${{ github.event.inputs.ref }}!"
          echo "Name - ${{ github.event.inputs.sha }}!"
