name: Kitchen Terraform Setup for Ops
on:
  repository_dispatch:
    types: [kitchen-terraform]
  workflow_dispatch:
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.ref }}
      - run: echo ${{ github.event.client_payload.sha }}
      - name: Pause for 25 seconds
        run: |
          sleep 25
